version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "s2mangas/team"
    assignees:
      - "s2mangas/team"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "s2mangas/team"
    assignees:
      - "s2mangas/team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"

  # Enable version updates for npm in core package
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "s2mangas/team"
    assignees:
      - "s2mangas/team"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "core"
      - "automated"

  # Enable version updates for npm in native package
  - package-ecosystem: "npm"
    directory: "/packages/native"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "s2mangas/team"
    assignees:
      - "s2mangas/team"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "native"
      - "automated"

  # Enable version updates for npm in react package
  - package-ecosystem: "npm"
    directory: "/packages/react"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "s2mangas/team"
    assignees:
      - "s2mangas/team"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "react"
      - "automated"
